version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: always
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    networks:
      - apoioentrega-network

networks:
  apoioentrega-network:
    driver: bridge 